name: Auto Recreate PR on Ready For Review

on:
  pull_request:
    types: [ready_for_review]

jobs:
  re_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Close original PR and create a new PR
        env:
          GH_TOKEN: ${{ secrets.ZAKEEx_GITHUB_TOKEN }}
        run: |
          # Only proceed if this PR was originally a draft
          if [[ "${{ github.event.pull_request.draft }}" == "false" ]]; then
            echo "PR is already ready for review (not a draft), skipping."
            exit 0
          fi

          PR_NUMBER="${{ github.event.pull_request.number }}"
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"

          # Close the original PR
          gh pr close "$PR_NUMBER" --delete-branch=false

          # Create a new PR (not draft)
          gh pr create \
            --head "$BRANCH_NAME" \
            --base "$BASE_BRANCH" \
            --title "$PR_TITLE" \
            --body "$PR_BODY"
